name: EMB
favicon: null
layout_spectrum: 0.00761
typography_spectrum: 0.07422
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e8ed4b'
    - '#1b747c'
    - '#69aad2'
    - '#2b2d23'
    - '#f390f0'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
