name: EMB
favicon: null
layout_spectrum: 0.24782
typography_spectrum: 0.04999
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d69382'
    - '#c2eef7'
    - '#93b1d5'
    - '#1b2b2b'
    - '#625856'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
