name: EMB
favicon: null
layout_spectrum: 0.24849
typography_spectrum: 0.2666
title: E-Marketing Buffet
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e7dbdf'
    - '#15221e'
    - '#33403c'
    - '#8d8c8a'
    - '#90604c'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
